spring.application.name=day-3

# Kafka Broker Address
spring.kafka.bootstrap-servers=localhost:9092

# Producer Settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer Settings
spring.kafka.consumer.group-id=bank-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Security & Trusted Packages
spring.kafka.consumer.properties.spring.json.trusted.packages=*