spring.application.name=day-4

# 1. Kafka Nerede?
spring.kafka.bootstrap-servers=localhost:9092

# 2. Gönderirken (Producer) Ayarlar?
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# 3. Al?rken (Consumer) Ayarlar?
# Buras? çok önemli: Day-4'te birden fazla grup kullanaca??z!
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Güvenilir paketleri belirtiyoruz (Hata almamak için)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Karakter kodlamas? hatas?n? önlemek için (Önceki projeden hat?rlars?n)
project.build.sourceEncoding=UTF-8
