spring.application.name=day-5
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Consumer'?n mesajlar? en ba?tan okumas? i�in (Test a?amas?nda hayat kurtar?r)
spring.kafka.consumer.auto-offset-reset=earliest

# Kafka Streams (Eksik olan k?s?m buras?yd?)
spring.kafka.streams.application-id=day-5-stream-app-v2
spring.kafka.streams.bootstrap-servers=localhost:9092

# Streams'in �al??mas? i�in bu Serde ayarlar? ?artt?r
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde
# Streams motorunu zorla ba?lat
spring.kafka.streams.auto-startup=true