spring.application.name=day-6
# Kafka'n?n çal??t??? adres
spring.kafka.bootstrap-servers=localhost:9092

# PRODUCER: Nesneyi JSON olarak gönder
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# CONSUMER: Gelen JSON'? nesneye çevir
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# JSON'? hangi s?n?fa çevirece?ini söylemen laz?m:
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.day_6
